personal_portfolio-project/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
	path('', views.all_blogs, name='all_blogs'),
	path('<int:blog_id>/', views.detail, name='detail'),
]

personal_portfolio-project/personal_portfolio/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
	path('', views.home, name='home'),
	path('admin/', admin.site.urls),
	#path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

personal_portfolio-project/blog/models.py
from django.db import models

# Create your models here.
class Blog(models.Model):
	title = models.CharField(max_length=100)
	preview = models.TextField()
	image = models.ImageField(upload_to='blogs/images')
	date = models.DateField()

	def __str__(self):
		return self.title

personal_portfolio-project/portfolio/models.py
from django.db import models
from tagging.fields import TagField
from markdownfield.models import MarkdownField, RenderedMarkdownField
from markdownfield.validators import VALIDATOR_STANDARD

# Create your models here.
class Project(models.Model):
	title = models.CharField(max_length=100)
	blurb = MarkdownField(rendered_field='blurb_rendered', validator=VALIDATOR_STANDARD, max_length=250, default='Insert blurb here')
	blurb_rendered = RenderedMarkdownField()
	description = MarkdownField(rendered_field='text_rendered', validator=VALIDATOR_STANDARD)
	text_rendered = RenderedMarkdownField()
	image = models.ImageField(upload_to='portfolio/images/', blank=True)
	url = models.URLField(blank=True)
	tags = TagField()

	def __str__(self):
		return self.title

personal_portfolio-project/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog

# Create your views here.
def all_blogs(request):
	blogs = Blog.objects.order_by('-date')
	return render(request, 'blog/all_blogs.html', {'blogs':blogs})

def detail(request, blog_id):
	blog = get_object_or_404(Blog, pk=blog_id)
	return render(request, 'blog/detail.html', {'blog':blog})

personal_portfolio-project/portfolio/views.py
from django.shortcuts import render
from .models import Project

# Create your views here.
def home(request):
	projects = Project.objects.all()
	return render(request, 'portfolio/home.html', {'projects':projects})

personal_portfolio-project/blog/templates/blog/all_blogs.html
{% extends 'portfolio/base.html' %}

{% block content %}
<div class='container my-5'>
<h1>Hello blog</h1>

<h2>Jocen has written  {{ blogs.count }} blog{{ blogs.count|pluralize }}</h2>

{% for blog in blogs %}

<a href="{% url 'blog:detail' blog.id %}"><h2>{{ blog.title }}</h2></a>
<h5>{{ blog.date|date:'M d Y'|upper }}</h5>
<p>{{ blog.preview|safe|truncatechars:100 }}</p>
<img src="{{ blog.image.url }}" width="320" height="240">

{% endfor %}

</div>
{% endblock %}

personal_portfolio-project/blog/templates/blog/detail.html
{% extends 'portfolio/base.html' %}

{% block content %}

<h1>{{ blog.title }}</h1>

<h2>--{{ blog.date|date:'F jS Y' }}--</h2>

{{ blog.preview|safe }}

{% endblock %}

personal_portfolio-project/portfolio/templates/portfolio/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

	{% load static %}
	{% load compress %}
	{% compress css %}
		<link type="text/x-scss" href="{% static 'bootstrap/bootstrap.scss' %}" rel="stylesheet" media="screen">
	{% endcompress %}

    <title>Josie Bytes</title>
  </head>
  <body>

	<nav class="navbar navbar-expand-lg navbar-dark background-primary" >
	<div class="container">
		<a class="navbar-brand text-custom-brand" href="{% url 'home' %}">Josie Bytes</a>
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
		<ul class="navbar-nav ml-auto">
			<li class="nav-item">
				<a class="nav-link" href="https://www.linkedin.com/in/jocenpagayona/">LinkedIn</a>
			</li>
		</ul>
		</div>
	</div>
	</nav>
	<div class="container">
		{% block content %}{% endblock %}
	</div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
	-->

	<footer class="footer pt-3 footer-custom background-primary">
		<div class="container">
		<!-- Copyright footnote -->
			<div class="row">
				<h6 class="col footer-text-custom">Josie Bytes © 2020</h6>
				<span class="col text-end">
					<address>Contact me <a class="address-link" href="mailto:joma.pagayona@gmail.com">here!</a></address>
				</span>
			</div>
		<!-- Contact link -->
		
		</div>
	</footer>
	</body>
</html>

personal_portfolio-project/portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}

{% block content %}

{% load static %}

<div class="row justify-content-center my-3">
	<div class="text-center col-lg-4">
	  <img src="{% static 'portfolio/jocen-glasses.jpg' %}" class="img-fluid">
	</div>
</div>

<div class="row justify-content-center mb-5">
	<div class="text-center">
		<h2 id="hometext" class="font-weight-bold">Mark Jocen Pagayona is an aspiring web developer and data analyst, currently exploring Python-Django and TypeScript!</h2>
	</div>
</div>

<div class="container my-3">
	<h2 class="mt-5">Portfolio</h2>
	<hr>
	<div class="row">
		{% for project in projects %}
		<div class="col-lg-4 col-md-6">
			<div class="card">

				{% if project.url %}
					<a href="{{ project.url }}">
						<img src="{{ project.image.url }}" class="card-img">
					</a>
				{% else %}

				<img src="{{ project.image.url}}" class="card-img">
				{% endif %}
				<h3 class="card-title my-3">{{ project.title }}</h3>
				<div class="card-body">{{ project.blurb_rendered | safe }}</div>

			</div>
		</div>
		{% endfor %}
	</div>
</div>

{% endblock %}